version: '3'

services:

  spacetrouble:
    command: go run cmd/space_trouble.go
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U space_trouble_user -d space_trouble" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=space_trouble_user
      - POSTGRES_PASSWORD=tabeo123
      - POSTGRESS_DB=space_trouble
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
